### ISSUE TITLE
Evaluate the necessity of the custom `modify_defaults()` function

### ISSUE THREAD

**Issue by Bisaloo** [epiverse-trace/datatagr#16]
I don't exactly remember if/why this function was necessary.

I also think that `modifyList()` has been updated in the last couple of years and might now be appropriate to use directly.

We should evaluate if `modify_defaults()` is really necessary or can be replaced by `modifyList()`.

In all cases, this function should have more & better comments:

- a comment about why it's necessary and how it differs from `modifyList()` so we don't have to go through this exercise again
- an explaining of why `keep.null` is necessary rather an affirmation that it is:
  https://github.com/epiverse-trace/datatagr/blob/d1d89459f8df0b5ac57636225c53cc243b3514c9/R/modify_defaults.R#L31

**Comment by chartgerink** [comment]
Thanks for this report 😊 Before I open the pull request where I address this, I document my evaluation as requested.

The primary code in `modify_defaults` that adds to the `modifyList` part is the following:

```
extra <- setdiff(names(x), names(defaults))
  if (strict && (length(extra) > 0L)) {
    stop(
      "Unknown variable types: ",
      toString(extra),
      "\n  ",
      "Use only known tags or set `allow_extra = TRUE`",
      call. = FALSE
    )
  }
```

This primarily is to check for known tags. Given that #22 indicates this can be dropped altogether, `modify_defaults` is indeed redundant. Will be removing this function and ensuring everything remains functional. 👍
