### ISSUE TITLE
Consider using *labelled* as backend

### ISSUE THREAD

**Issue by thibautjombart** [epiverse-trace/datatagr#32]
It seems the package [{labelled}](https://github.com/larmarange/labelled) is doing something very similar to our tagging system. We should consider using it as a backend. Some considerations:

- [ ] check it can actually replace current functionalities
- [ ] check if it adds useful functionalities
- [ ] check how many deps would be pulled in

**Comment by Bisaloo** [comment]
My recommendation would be to:

- indeed set `attr(, "label")` directly, without taking labelled as a dependency
- pull the plug and make a breaking change to implement tagging by column, which seems to be a more commonly accepted standard (i.e., option (2) in your next steps section)

**Comment by chartgerink** [comment]
Very well 😄 

![A GIF of Bill Nye pulling an extension cord plug, as a way of illustrating that we just pulled the plug and are moving ahead with making the breaking change Hugo proposed.](https://media.giphy.com/media/cCbfAZrva7sjIvsI5H/giphy.gif?cid=790b7611epvd07wzwo44mvx1twkf1cadb6nvgyqzixywfr80&ep=v1_gifs_search&rid=giphy.gif&ct=g)
