### ISSUE TITLE
Use `withr::with_options()` in `lost_tags_action.R`

### ISSUE THREAD

**Issue by chartgerink** [epiverse-trace/datatagr#9]
I introduced a `# nolint` to ensure our checks pass in #8 - this issue is to ensure we track the work needed to not ignore the linter and provide a proper alternative, that complies with the linter.

This will mean replacing the `options()` calls with the functionality provided in `withr` to do this safely.

**Comment by Bisaloo** [comment]
I think it's one of the rare cases where `# nolint` is appropriate. withr will help to modify options temporarily, which is what we want in most cases but not here.

Here, we want to be able to change the `options()` for the entire duration of the session. This is an uncommon need hence why lintr warns against it.

An alternative to avoid the nolint comment would be to update the lintr settings, as done in linelist:

https://github.com/epiverse-trace/linelist/blob/9e49d071844626454eea9766f7eadaba12121907/.lintr#L13
